name: Run Android tests in GitHub Runner

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install Appium
        run: |
          npm install -g appium@2.5.1
          npm install -g appium-uiautomator2-driver@3.0.1

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-levels: 34  # Réglage du niveau d'API sur 34
          target: default
          arch: x86_64
          channel: stable

      - name: Accept SDK licenses
        run: |
          echo y | sdkmanager --licenses

      - name: Create AVD
        run: |
          echo no | avdmanager create avd -n test -k "system-images;android-34;google_apis;x86_64" --force

      - name: Start emulator
        run: emulator -avd test -no-window -no-audio -no-boot-anim &

      - name: Wait for emulator to start
        run: sleep 60

      - name: Start Appium server
        run: |
          appium &
          nohup appium > appium.log 2>&1 &
          sleep 60

      - name: Verify Appium server is running
        shell: pwsh
        run: |
          $maxRetries = 10
          $retryCount = 0
          $url = "http://127.0.0.1:4723/status"
          
          while ($retryCount -lt $maxRetries) {
            try {
              $response = Invoke-WebRequest -Uri $url -UseBasicParsing
              if ($response.StatusCode -eq 200) {
                Write-Host "Appium server is running"
                break
              }
            } catch {
              Write-Host "Appium server is not running, retrying..."
              Start-Sleep -Seconds 5
              $retryCount++
            }
          }
          
          if ($retryCount -eq $maxRetries) {
            Write-Host "Appium server failed to start after $maxRetries attempts"
            exit 1
          }

      - name: Run Android Tests
        run: |
          echo "JAVA_HOME: $env:JAVA_HOME"
          mvn -Dtest=TestRunner test

      - name: Display Appium Logs
        run: |
          cat appium.log
