name: Appium Selenium Tests on Android Emulator

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Appium Selenium Tests on Android Emulator
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Download and set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '30'

      - name: Check for processes using port 5037
        run: |
          netstat -ano | findstr :5037 || echo "No process using port 5037"
          echo "Killing any ADB server running on port 5037"
          adb kill-server || true

      - name: Start ADB server
        run: adb start-server

      - name: Wait for ADB server to start
        run: |
          sleep 5
          adb devices

      - name: Start Android Emulator
        run: |
          emulator -avd Pixel_6_API_30 -no-window -no-audio -no-boot-anim -accel auto -gpu host &

      - name: Wait for Emulator to start
        run: |
          sleep 60  # Wait for the emulator to boot up
          adb wait-for-device
          adb shell input keyevent 82  # Simulate unlock screen
          adb shell getprop sys.boot_completed | findstr /C:"1"

      - name: Run Appium Tests
        run: mvn test -Denv=local
