name: Run Android tests in GitHub Runner

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "Setting up environment variables"
          echo "ANDROID_HOME=C:/Users/runneradmin/Library/Android/sdk" >> $GITHUB_ENV
          echo "${{ github.workspace }}/emulator" >> $GITHUB_PATH
          echo "${{ github.workspace }}/platform-tools" >> $GITHUB_PATH
          echo "${{ github.workspace }}/tools" >> $GITHUB_PATH
          echo "${{ github.workspace }}/tools/bin" >> $GITHUB_PATH
          echo "ANDROID_HOME is set to: $ANDROID_HOME"
          echo "PATH is set to: $PATH"
        shell: bash

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install Appium
        run: |
          npm install -g appium@2.5.1
          appium -v
        shell: bash

      - name: Install Appium Doctor
        run: |
          npm install -g appium-doctor
          appium-doctor --version
        shell: bash

      - name: Install UIAutomator2 driver for Appium
        run: |
          appium driver install uiautomator2@3.0.1
        shell: bash

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: |
          sdkmanager --install 'system-images;android-34;google_apis;x86_64'
          sdkmanager --install 'platform-tools'
          sdkmanager --install 'emulator'
      - name: Accept SDK licenses
        run: |
          yes | sdkmanager --licenses
        shell: bash

      - name: Run Appium Doctor
        run: |
          appium-doctor --android
        shell: bash

      - name: Create AVD
        run: |
          echo no | avdmanager create avd -n Pixel_5_API_34 -k "system-images;android-34;google_apis;x86_64" --force
        timeout-minutes: 10

      - name: List available AVDs
        run: |
          avdmanager list avd
          ls $HOME/.android/avd
        shell: bash

      - name: Start emulator
        run: |
          nohup emulator -avd Pixel_5_API_34 -no-audio -no-window &
          adb wait-for-device
        shell: bash

      - name: Verify emulator is running
        run: |
          adb devices

      - name: Start Appium server
        run: |
          nohup appium &
          sleep 10
        shell: bash

      - name: Verify Appium server is running
        run: |
          curl http://127.0.0.1:4723/status
        shell: bash

      - name: Run Android Tests
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          echo "ANDROID_HOME: $ANDROID_HOME"
          echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
          ls
          echo "Running Maven tests..."
          mvn -Dtest=TestRunner test
          echo "Maven tests completed."
