name: Test Appium avec Genymotion et Rapport Allure

on: [push]

jobs:
  test-appium:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Cloner le dépôt
      - uses: actions/checkout@v3

      # Étape 2 : Installer Node.js 16
      - name: Installer Node.js 16
        run: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
          apt-get install -y nodejs

      # Étape 3 : Installer Appium
      - name: Installer Appium
        run: npm install -g appium

      # Étape 4 : Lancer le serveur Appium
      - name: Lancer le serveur Appium
        run: |
          appium &

      # Étape 5 : Télécharger l'image Android
      - name: Télécharger l'image Android
        uses: actions/download-artifact@v4
        with:
          name: genymotion-image
          path: android-emulator

      # Étape 6 : Installer adb et Java 17
      - name: Installer adb et Java 17
        run: |
          sudo apt-get update && sudo apt-get install -y android-tools-adb
          wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2Fotn%2Fjava%2Fdownload%2Findex.html%3B secure%3Dfalse%3B HttpOnly%3B SameSite%3DNone%3B Path%3D%2F; oraclelicense=accept-securebackup-cookie" -O jdk-17_linux-x64_bin.rpm http://download.oracle.com/otn-pub/java/jdk/17.0.8+j9/languagesupport/release/jdk-17_linux-x64_bin.rpm
          sudo rpm -ivh jdk-17_linux-x64_bin.rpm

      # Étape 7 : Démarrer l'emulateur Genymotion
      - name: Démarrer l'emulateur Genymotion
        run: |
          cd android-emulator
          ./start.sh Pixel_6_API_30

      # Étape 8 : Exécuter les tests Appium
      - name: Exécuter les tests Appium
        run: |
          # Exécutez vos commandes de test Appium ici
          # Par exemple :
          # npx appium-test --app ./android-app.apk

      # Étape 9 : Arrêter le serveur Appium
      - name: Arrêter le serveur Appium
        run: pkill appium

      # Étape 10 : Générer le rapport Allure
      - name: Générer le rapport Allure
        uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # Étape 11 : Construire le rapport Allure
      - name: Construire le rapport Allure
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      # Étape 12 : Déployer le rapport sur GitHub Pages
      - name: Déployer le rapport sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        env:
          PERSONAL_TOKEN: ${{ secrets.TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
