name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  android-emulator-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y \
              apt-transport-https \
              ca-certificates \
              curl \
              software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository \
              "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
              $(lsb_release -cs) \
              stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce
          sudo usermod -aG docker $USER
          newgrp docker

    

      - name: Install Node.js and Appium
        run: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install -g appium

      - name: Run Android Emulator container
        run: |
          docker run -d -p 6080:6080 -e EMULATOR_DEVICE="Samsung Galaxy S10" -e WEB_VNC=true --device /dev/kvm --name android-container budtmo/docker-android:emulator_11.0

      - name: Wait for emulator to start
        run: |
          echo "Waiting for Android Emulator to start..."
          sleep 60 # Adjust this sleep duration based on how long the emulator takes to start

      - name: Run Appium Server
        run: appium &

      - name: Wait for Appium Server to start
        run: |
          echo "Waiting for Appium Server to start....."
          sleep 10 # Adjust this sleep duration based on how long the server takes to start

      - name: Run Android Tests
        run: |
          mvn test -Denv=local
          echo "Maven tests completed."
