name: Android Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Appium
        run: npm install -g appium

      - name: Start Appium server
        run: appium &

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-levels: 30
          target: default
          arch: x86_64

      - name: Accept Android SDK licenses
        run: |
          $sdkManager = "${ANDROID_SDK_ROOT}\cmdline-tools\latest\bin\sdkmanager.bat"
          Start-Process -Wait -NoNewWindow -FilePath $sdkManager -ArgumentList "--licenses" -PassThru | ForEach-Object { $_.StandardInput.WriteLine("y") }

      - name: Install dependencies
        run: mvn install

      - name: Run tests
        run: mvn test -PAndroid
