name: Run Android tests in GitHub Runner

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install Appium
        run: |
          npm install -g appium@latest
          appium -v
        shell: bash

      - name: Install Appium Doctor
        run: |
          npm install -g appium-doctor
          appium-doctor --version
        shell: bash

      - name: Install UIAutomator2 driver for Appium
        run: |
          appium driver install uiautomator2@3.0.1
        shell: bash

      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: '30'
          target: 'google_apis'
          profile: 'pixel_6'

      - name: Run Appium Server
        run: appium &
        shell: bash

      - name: Wait for Emulator to start
        run: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
        timeout-minutes: 5

      - name: Run Android Tests
        run: mvn test -Denv=local
