name: Appium Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set up Node.js 16.13.0
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install Appium
        run: npm install -g appium

      - name: Install Appium Doctor
        run: npm install -g appium-doctor

      - name: Install UIAutomator2 Driver
        run: npm install -g appium-uiautomator2-driver

      - name: Run Appium Doctor
        run: appium-doctor --android

      - name: Download and set up Android SDK
        uses: malvcr/setup-android-sdk@v1
        with:
          api-levels: '30'
          target: 'android-30'
          build-tools: '30.0.3'

      - name: Start Android Emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
          adb wait-for-device
          adb shell input keyevent 82 &

      - name: Build with Maven
        run: mvn clean install

      - name: Run Appium server
        run: appium &
        env:
          PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH

      - name: Run Appium Tests
        run: mvn test
