name: Appium Android

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [30]
        target: [default]
        arch: [arm64-v8a]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install Appium
        run: |
          npm install -g appium@latest
          appium -v

      - name: Start Appium Server
        run: appium &> appium.log &
        shell: bash

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: Nexus 6
          emulator-options: '-no-snapshot -noaudio -no-boot-anim -accel off'
          disable-animations: true
          script: echo "Emulator is ready"

      - name: Wait for Android Emulator to be ready
        run: |
          adb wait-for-device
          adb shell getprop sys.boot_completed | grep -m 1 '1' || exit 1
          adb shell input keyevent 82

      - name: Run Appium Tests
        run: mvn clean test -PAndroid
