name: Android Appium Selenium CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force;
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Download and set up Android SDK
        run: |
          choco install -y android-sdk;
          echo "sdk.dir=C:\\Android\\android-sdk" > local.properties;
          echo "ANDROID_HOME=C:\\Android\\android-sdk" >> $env:GITHUB_ENV;
          echo "PATH=C:\\Android\\android-sdk\\platform-tools;C:\\Android\\android-sdk\\emulator;C:\\Android\\android-sdk\\cmdline-tools\\latest\\bin;$env:PATH" >> $env:GITHUB_ENV;
          $env:ANDROID_HOME="C:\\Android\\android-sdk";
          $env:PATH="$env:PATH;C:\\Android\\android-sdk\\platform-tools;C:\\Android\\android-sdk\\emulator;C:\\Android\\android-sdk\\cmdline-tools\\latest\\bin";
          sdkmanager --update;
          echo "y" | sdkmanager --licenses;
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "system-images;android-30;google_apis;x86_64" "emulator"

      - name: Set up environment variables
        run: |
          echo "ANDROID_HOME=C:\\Android\\android-sdk" >> $env:GITHUB_ENV;
          echo "PATH=C:\\Android\\android-sdk\\platform-tools;C:\\Android\\android-sdk\\emulator;C:\\Android\\android-sdk\\cmdline-tools\\latest\\bin;$env:PATH" >> $env:GITHUB_ENV

      - name: Start ADB server
        run: adb start-server

      - name: Create and start emulator
        run: |
          echo no | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force;
          start /B "" "%ANDROID_HOME%\\emulator\\emulator.exe -avd test -no-snapshot-save -no-audio -no-window -gpu off";
          adb wait-for-device;
          adb shell input keyevent 82

      - name: Wait for emulator to boot
        run: |
          $bootanim = "";
          while ($bootanim -ne "stopped") {
            $bootanim = adb -e shell getprop init.svc.bootanim;
            Start-Sleep -Seconds 1
          }

      - name: Install Maven
        run: choco install -y maven

      - name: Install dependencies
        run: mvn install

      - name: Run Appium server
        run: |
          npm install -g appium;
          start /B appium -p 4723;
          Start-Sleep -Seconds 10

      - name: Run tests
        run: mvn test
