name: Android Appium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ runner.tool_cache }}/android-sdk
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      PATH: ${{ runner.tool_cache }}/android-sdk/cmdline-tools/latest/bin:${{ runner.tool_cache }}/android-sdk/platform-tools:${{ runner.tool_cache }}/android-sdk/emulator:$PATH

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js 16.13.0
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.0'

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar unzip lib32stdc++6 lib32z1 qemu-kvm
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
          unzip -q commandlinetools-linux-7302050_latest.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86_64" "emulator"

      - name: Install Appium and Appium Doctor
        run: |
          npm install -g appium@latest
          npm install -g appium-doctor
          appium-doctor --android

      - name: Start Android Emulator
        run: |
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "pixel"
          $ANDROID_SDK_ROOT/emulator/emulator-headless -avd test -no-boot-anim -no-window -no-audio -no-snapshot &
          adb wait-for-device
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0
          adb shell input keyevent 82

      - name: Wait for Emulator to finish booting
        run: |
          adb wait-for-device shell getprop init.svc.bootanim | grep stopped

      - name: Start Appium Server
        run: appium &
        shell: bash

      - name: Wait for Appium Server to start
        run: sleep 10

      - name: Build and run tests with Maven
        run: |
          mvn clean install
          mvn test
