name: Android Tests

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Appium
        run: |
          npm install -g appium@latest
          appium -v

      - name: Install Appium Doctor
        run: |
          npm install -g appium-doctor
          appium-doctor --version

      - name: Install UIAutomator2 driver for Appium
        run: |
          appium driver install uiautomator2@3.0.1

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: |
          sdkmanager --install 'system-images;android-30;google_apis;x86_64'
          sdkmanager --install 'platform-tools'
          sdkmanager --install 'emulator'

      - name: Accept SDK licenses
        run: |
          yes | sdkmanager --licenses

      - name: Create AVD
        run: |
          echo no | avdmanager create avd -n Nexus_6_API_30 -k "system-images;android-30;google_apis;x86_64" --force

      - name: Start emulator
        run: |
          emulator -avd Nexus_6_API_30 -no-audio -no-window -gpu swiftshader_indirect &
          adb wait-for-device
          sleep 180
          adb shell input keyevent 82

      - name: Verify emulator is running
        run: |
          adb devices
          adb shell getprop init.svc.bootanim | grep -m 1 stopped

      - name: Start Appium server
        run: |
          appium &

      - name: Verify Appium server is running
        run: |
          curl http://127.0.0.1:4723/status
          if [ $? -eq 0 ]; then
            echo "Appium server is running"
          else
            echo "Appium server is not running"
            exit 1
          fi

      - name: Run Android Tests
        run: |
          echo "Running Maven tests..."
          mvn test -Denv=local
          echo "Maven tests completed."
