name: Appium Selenium Tests on Android Emulator

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Appium Selenium Tests on Android Emulator
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Download and set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '30'

      - name: Start Android Emulator
        run: |
          cd $env:ANDROID_HOME\emulator
          .\emulator -avd Pixel_6_API_30 -no-window -no-audio -no-boot-anim -accel auto -gpu host &
      

      - name: Wait for Emulator to start
        run: |
          adb wait-for-device
          sleep 90

      - name: Run Appium Tests
        run: mvn test -Denv=local
