name: Run Appium tests on Android Emulator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install -g appium appium-doctor
          appium-doctor --version
          npm install

      - name: Install UIAutomator2 driver for Appium
        run: |
          appium plugin install --source=npm appium-uiautomator2-driver@3.0.1

      - name: Start Android Emulator
        run: |
          echo no | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64"
          emulator -avd test -no-audio -no-window &
          android-wait-for-emulator

      - name: Run Appium tests
        run: |
          appium &
          mvn clean test

      - name: Stop emulator
        run: |
          adb emu kill
