name: Appium CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [34]
        target: [default]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Install Maven dependencies
        run: mvn install

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64

      - name: Create and Start Emulator
        run: |
          echo "y" | sdkmanager --install "system-images;android-${{ matrix.api-level }};${{ matrix.target }};x86_64"
          avdmanager create avd -n test -k "system-images;android-${{ matrix.api-level }};${{ matrix.target }};x86_64" --device "pixel"
          emulator -avd test -no-audio -no-window &
          adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install Appium
        run: npm install -g appium

      - name: Start Appium Server
        run: appium &

      - name: Wait for Appium Server to Start
        run: |
          while ! nc -z localhost 4723; do   
            echo "Waiting for Appium server...";
            sleep 1;
          done;
          echo "Appium server is running";

      - name: Run Appium Tests
        run: |
          # Insert your command to run tests here
          # Example: mvn test -Dtest=runner.TestRunner
          echo "Running tests with Maven"
          mvn test -Dtest=runner.TestRunner

      - name: Terminate Emulator
        run: adb emu kill
