name: Appium Tests with Firebase Test Lab

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download and extract Android SDK
        run: |
          mkdir -p $HOME/android-sdk
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-win-7302050_latest.zip
          Expand-Archive -Path sdk-tools.zip -DestinationPath $HOME/android-sdk
          $env:ANDROID_SDK_ROOT = "$HOME/android-sdk"
          & $env:ANDROID_SDK_ROOT\cmdline-tools\bin\sdkmanager --sdk_root=$env:ANDROID_SDK_ROOT "platforms;android-30"
        shell: pwsh
        env:
          JAVA_HOME: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\17.0.11-9\x64

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'  # Mettez à jour vers une version de Node.js >= 18
          architecture: x64     # Spécifiez l'architecture si nécessaire

      - name: Install Appium
        run: npm install -g appium

      - name: Build and assemble APK
        run: mvn clean install -DskipTests=true

      - name: Start Appium Server
        run: cmd /c start appium

      - name: Run Appium Tests
        run: mvn test

      - name: Stop Appium Server
        run: taskkill /IM node.exe /F

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase CLI
        run: firebase login:ci --token "${{ secrets.FIREBASE_CI_TOKEN }}"

      - name: Upload APKs to Firebase Test Lab
        run: |
          firebase appdistribution:distribute YOUR_APP_PATH --app PACKAGE_NAME
          firebase appdistribution:tester:apps:add YOUR_TEST_PATH --app PACKAGE_NAME

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ${{ github.workspace }}/firebase_test_lab_results
