name: Android UI Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js 16.13.0
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.0'

      - name: Install Appium
        run: npm install -g appium

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          target: default
          arch: x86_64

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Create AVD
        run: |
          echo "no" | avdmanager create avd -n Pixel_6_API_30 -k "system-images;android-30;google_apis;x86_64" --device "pixel_6"

      - name: Start xvfb
        run: |
          Xvfb :1 -screen 0 1280x1024x24 &
          export DISPLAY=:1

      - name: Start AVD
        run: |
          $ANDROID_HOME/emulator/emulator -avd Pixel_6_API_30 -no-window -no-audio -no-snapshot &
          adb wait-for-device
          adb shell settings put global window_animation_scale 0.0
          adb shell settings put global transition_animation_scale 0.0
          adb shell settings put global animator_duration_scale 0.0

      - name: Wait for emulator to boot
        run: |
          adb shell getprop init.svc.bootanim | grep -m 1 stopped
          adb shell input keyevent 82

      - name: Run tests
        run: mvn test -Denv=local
