name: Appium Tests

on:
  push:
    branches:
      - master


jobs:
  test:

    runs-on: ubuntu-latest

    services:
      appium:
        image: appium/appium
        ports:
          - 4723:4723

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install dependencies
        run: mvn install

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: Pixel_5
          script: echo "no" | avdmanager create avd -n test -k "system-images;android-30;default;x86_64"

      - name: Run Android tests
        run: mvn test -PAndroid

    # Uncomment and configure if you also want to run iOS tests
    # - name: Start iOS Simulator
    #   run: |
    #     brew install --cask xquartz
    #     brew install --cask ios-simulator
    #     sudo xcode-select --switch /Applications/Xcode.app
    #     sudo xcodebuild -runFirstLaunch
    #     xcrun simctl boot "iPhone 13"
    #   shell: bash

    # - name: Run iOS tests
    #   run: mvn test -PIOS
