name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/adoptopenjdk-17-hotspot-amd64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: |
          echo "Running Maven tests..."
          mvn test -Denv=local
          echo "Maven tests completed."

    # Ajoutez d'autres étapes de test et de déploiement si nécessaire
