name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  android-emulator-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Install Node.js and Appium
        run: |
          sudo apt-get install -y nodejs npm
          npm install -g appium

      - name: Install Android SDK Platform Tools (adb)
        run: |
          sudo apt-get install -y android-sdk-platform-tools

      - name: Set up ANDROID_HOME and ADB
        run: |
          export ANDROID_HOME=$HOME/Android/Sdk
          export PATH=$ANDROID_HOME/platform-tools:$PATH
        shell: bash

      - name: Install UiAutomator2 Driver
        run: |
          appium driver install uiautomator2

      - name: Start Android Emulator in Docker
        run: |
          docker run -d -p 5554:5554 -p 5555:5555 -p 6080:6080 \
            -e EMULATOR_DEVICE="Samsung Galaxy S10" \
            -e WEB_VNC=true --device /dev/kvm \
            --name android-container budtmo/docker-android:emulator_11.0

      - name: Wait for Emulator
        run: |
          adb start-server
          for i in {1..60}; do
            adb connect localhost:5555
            if adb devices | grep emulator; then
              echo "Emulator is ready!"
              break
            else
              echo "Waiting for emulator to be ready..."
              sleep 10
            fi
          done

      - name: Start Appium Server
        run: appium &

      - name: Run Android Tests
        run: |
          mvn test -Denv=local

      - name: Get Allure history
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.TOKEN }}
        with:
          publish_branch: gh-pages
          publish_dir: allure-history
