name: Appium Android Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        android-version: [11]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Android SDK
        uses: android-sdk-action/setup@v1
        with:
          tools: 'platform-tools,build-tools-30.0.3,android-11'

      - name: Install dependencies
        run: |
          npm ci

      - name: Install Appium
        run: |
          npm install -g appium

      - name: Run tests
        env:
          ANDROID_VERSION: ${{ matrix.android-version }}
        run: |
          appium doctor
          appium run android --app ./src/main/resources/ApiDemos-debug.apk --version $ANDROID_VERSION
