name: Appium Selenium Tests on Android Emulator

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Appium Selenium Tests on Android Emulator
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Download and set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '35'
        env:
          ANDROID_HOME: ${{ steps.setup-android.outputs.android-sdk }}
      - name: Install ADB
        run: sdkmanager "platform-tools"

      - name: Install Appium
        run: npm install appium@2.5.1

      - name: Start Android Emulator
        run: |
          $ANDROID_HOME/platform-tools/emulator  -avd Pixel_6_API_30 -no-window -no-audio -no-boot-anim -accel auto -gpu host 
          adb wait-for-device

      - name: Check Emulator Status via ADB
        run: adb devices

      - name: Start Appium Server
        run: appium

      - name: Run Appium Tests
        run: mvn test -Denv=local
