name: Android Appium Selenium CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      xvfb:
        image: selenium/standalone-chrome
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Download Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-30" "build-tools;30.0.3" "system-images;android-30;google_apis;x86_64" "emulator"

      - name: Start ADB server
        run: adb start-server

      - name: Create and start emulator
        run: |
          echo "no" | $HOME/android-sdk/cmdline-tools/bin/avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force
          $HOME/android-sdk/emulator/emulator -avd test -no-snapshot-save -no-audio -no-window -gpu off &
          adb wait-for-device
          adb shell input keyevent 82

      - name: Wait for emulator to boot
        run: |
          bootanim=""
          until [[ "$bootanim" =~ "stopped" ]]; do
            bootanim=`adb -e shell getprop init.svc.bootanim 2>&1 &
            sleep 1
          done

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Install dependencies
        run: mvn install

      - name: Run Appium server
        run: |
          npm install -g appium
          appium -p 4723 &
          sleep 10

      - name: Run tests
        run: mvn test
