name: Appium CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        api-level: [34]
        target: [google_apis]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Install Maven dependencies
        run: mvn install

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64

      - name: Create and Start Emulator
        run: |
          echo "y" | sdkmanager --install "system-images;android-${{ matrix.api-level }};${{ matrix.target }};x86_64"
          avdmanager create avd -n Pixel_5 -k "system-images;android-${{ matrix.api-level }};${{ matrix.target }};x86_64" --device "pixel"
          emulator -avd Pixel_5 -no-window -no-audio &

      - name: Wait for Emulator to Boot
        run: adb wait-for-device shell "while [[ -z \$(getprop sys.boot_completed) ]]; do sleep 1; done;"

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install Appium
        run: npm install -g appium

      - name: Start Appium Server
        run: appium &

      - name: Run Appium Tests with Maven
        run: mvn test -P test-runner
