name: Run Android tests in GitHub Runner

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install Appium
        run: |
          npm install -g appium@2.5.1
          appium -v
        shell: bash

      - name: Install Appium Doctor
        run: |
          npm install -g appium-doctor
          appium-doctor --version
        shell: bash

      - name: Install UIAutomator2 driver for Appium
        run: |
          appium driver install uiautomator2@3.0.1
        shell: bash

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: |
          sdkmanager --install 'system-images;android-30;google_apis;x86_64'
          sdkmanager --install 'platform-tools'
          sdkmanager --install 'emulator'

      - name: Accept SDK licenses
        run: |
          echo y | sdkmanager --licenses
        shell: bash

      - name: Run Appium Doctor
        run: |
          appium-doctor --android
        shell: bash

      - name: Create AVD
        run: |
          echo no | avdmanager create avd -n Pixel_6_API_30 -k "system-images;android-30;google_apis;x86_64" --force
        timeout-minutes: 10
        shell: bash

      - name: List available AVDs
        run: |
          avdmanager list avd
          dir $HOME\.android\avd
        shell: bash

      - name: Start emulator
        run: |
          $env:ANDROID_HOME = ${{ steps.setup-android.outputs.android-home }}
          $env:PATH += ";$env:ANDROID_HOME\emulator;$env:ANDROID_HOME\platform-tools"
          cd $env:ANDROID_HOME\emulator
          .\emulator.exe -avd Pixel_6_API_30 -no-audio -no-window &
          Start-Sleep -Seconds 60
        shell: pwsh

      - name: Verify emulator is running
        run: |
          adb devices
        shell: pwsh

      - name: Wait for emulator to boot
        run: |
          $bootanim = ""
          while ($bootanim -notmatch "stopped") {
            Start-Sleep -Seconds 5
            $bootanim = adb -s emulator-5554 shell getprop init.svc.bootanim 2>&1
            Write-Host "bootanim status: $bootanim"
          }
        shell: pwsh

      - name: Start Appium server
        run: |
          appium --address 127.0.0.1 --port 4723 &
          Start-Sleep -Seconds 10
        shell: pwsh

      - name: Verify Appium server is running
        run: |
          curl http://127.0.0.1:4723/wd/hub/status
          if ($?) { Write-Host "Appium server is running" } else { Write-Host "Appium server is not running"; exit 1 }
        shell: pwsh

      - name: Run Android Tests
        run: |
          echo "JAVA_HOME: $env:JAVA_HOME"
          echo "ANDROID_HOME: $env:ANDROID_HOME"
          echo "ANDROID_SDK_ROOT: $env:ANDROID_SDK_ROOT"
          Get-ChildItem
          echo "Running Maven tests..."
          mvn test -Denv=local
          echo "Maven tests completed."
        env:
          ANDROID_HOME: ${{ steps.setup-android.outputs.android-home }}
          ANDROID_SDK_ROOT: ${{ steps.setup-android.outputs.android-home }}
        shell: pwsh
