name: Appium Android Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      PATH: /usr/local/lib/android/sdk/emulator:$PATH
      PATH: /usr/local/lib/android/sdk/tools:$PATH
      PATH: /usr/local/lib/android/sdk/tools/bin:$PATH
      PATH: /usr/local/lib/android/sdk/platform-tools:$PATH

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Appium
        run: npm install -g appium@latest

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          emulator: true
          platform: android-30
          arch: x86_64

      - name: Install system images
        run: |
          yes | sdkmanager --install "system-images;android-30;google_apis;x86_64"

      - name: Start AVD
        run: |
          avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force --abi google_apis/x86_64 --device "pixel"
          emulator -avd test -no-window -no-audio -gpu swiftshader_indirect &
          adb wait-for-device
          adb shell settings put global window_animation_scale 0.0
          adb shell settings put global transition_animation_scale 0.0
          adb shell settings put global animator_duration_scale 0.0
          adb shell input keyevent 82

      - name: Wait for emulator to boot
        run: |
          adb shell getprop init.svc.bootanim | grep -m 1 stopped

      - name: Install Maven dependencies
        run: mvn install -DskipTests

      - name: Start Appium Server
        run: appium &

      - name: Run Appium tests
        run: mvn test

      # Allure Report integration
      - name: Get Allure history
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.TOKEN }}
        with:
          publish_branch: gh-pages
          publish_dir: allure-report
