name: Android Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configurer Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptium'

      - name: Installer Node.js 16.13.0
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.0'

      - name: Installer Android SDK
        run: |
          sudo apt-get update && sudo apt-get install -y android-studio

      - name: Démarrer l'émulateur Android
        run: |
          adb devices
          adb shell input keyevent 82

      - name: Installer les dépendances Maven
        run: mvn install

      - name: Exécuter les tests Appium
        run: mvn test
