name: Afficher le répertoire de travail

on:
  push:
    branches:
      - master

jobs:
  display_workspace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Afficher le répertoire de travail
        run: echo $GITHUB_WORKSPACE

      - name: Lister le contenu du répertoire de travail
        run: ls $GITHUB_WORKSPACE
