name: Run Android tests in GitHub Runner

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install Appium
        run: |
          npm install -g appium@latest
          appium -v

      - name: Install Appium Doctor
        run: |
          npm install -g appium-doctor
          appium-doctor --version

      - name: Install UIAutomator2 driver for Appium
        run: |
          appium driver install uiautomator2@3.0.1

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-levels: 30
          components: tools, platform-tools

      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          profile: pixel_6
          script: |
            adb wait-for-device
            for i in {1..10}; do
              adb shell getprop sys.boot_completed | grep -m 1 '1' && echo 'Emulator is ready' && break
              echo 'Waiting for emulator to start...'
              sleep 30
            done

      - name: Run Appium Server
        run: appium &

      - name: Run Android Tests
        run: mvn test -Denv=local
