name: Appium Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install Appium
        run: |
          npm install -g appium@latest
          appium -v

      - name: Start Appium Server
        run: appium &> appium.log &
        shell: bash

      - name: Start Emulator
        run: |
          /usr/local/lib/android/sdk/emulator -avd Pixel_6_API_30 -no-window -no-audio -no-boot-anim &
        env:
          DISPLAY: ":0"

      - name: Wait for Emulator to be ready
        run: |
          adb wait-for-device
          adb shell getprop sys.boot_completed | grep -m 1 '1' || exit 1
          adb shell input keyevent 82

      - name: Run Appium Tests
        run: mvn clean test -Denv=local
