name: Appium Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set up Node.js 16.13.0
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install Appium
        run: npm install -g appium

      - name: Install Appium Doctor
        run: npm install -g appium-doctor

      - name: Install UIAutomator2 Driver
        run: npm install -g appium-uiautomator2-driver

      - name: Run Appium Doctor
        run: appium-doctor --android

      - name: Download Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O android-commandline-tools.zip
          unzip android-commandline-tools.zip -d $HOME/android-sdk
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv $HOME/android-sdk/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          export PATH=$ANDROID_SDK_ROOT/platform-tools:$PATH
          export PATH=$ANDROID_SDK_ROOT/emulator:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86_64" "emulator"

      - name: Create Android Emulator
        run: |
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force

      - name: Start Android Emulator
        run: |
          $ANDROID_SDK_ROOT/emulator/emulator -avd test -no-audio -no-window &
          adb wait-for-device
          adb shell input keyevent 82 &

      - name: Build with Maven
        run: mvn clean install

      - name: Run Appium server
        run: appium &
        env:
          PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH

      - name: Run Appium Tests
        run: mvn test
