name: Appium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set up Node.js 16.13.0
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install Appium
        run: npm install -g appium

      - name: Install Appium Doctor
        run: npm install -g appium-doctor

      - name: Install UIAutomator2 Driver
        run: appium driver install uiautomator2@3.0.1

      - name: Run Appium Doctor
        run: appium-doctor --android

      - name: Start Appium Server
        run: appium &

      - name: Start Android Emulator and run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          script: |
            adb wait-for-device
            adb shell input keyevent 82 &
            mvn clean test -Denv=local -e
