name: Run Android tests in GitHub Runner

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        api-level: [34]  # Choisir le niveau d'API Android approprié

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install dependencies
        run: |
          npm install -g appium@v2.5.1  # Installer Appium

      - name: Install UIAutomator2 driver for Appium
        run: |
          appium driver install uiautomator2@3.0.1    

      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Install Android SDK packages
        run: |
          sdkmanager --install 'system-images;android-25;google_apis;x86_64'
          sdkmanager --install 'platform-tools'
          sdkmanager --install 'emulator'

      - name: Accept SDK licenses
        run: |
          echo y | sdkmanager --licenses

      - name: Create AVD
        run: |
          echo no | avdmanager create avd -n test -k "system-images;android-25;google_apis;x86_64" --force

      - name: Run Appium Android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}  # Niveau d'API Android
          force-avd-creation: false  # Ne pas forcer la création de l'AVD
          disable-animations: true  # Désactiver les animations de l'émulateur
          script: |
            appium -v  # Vérifier la version d'Appium
            appium &>/dev/null &  # Démarrer Appium en arrière-plan
            adb devices  # Afficher les appareils Android connectés

      - name: Run tests with Maven
        run: mvn clean test -Dtest=TestRunner
        working-directory: ${{ github.workspace }}/Appium2.0_Project2
        env:
            ANDROID_HOME: ${{ github.workspace }}/android-sdk
            ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk.
