name: Appium CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ui-tests:
    strategy:
      matrix:
        api-level: [28]
        target: [default]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Node.js and Appium
        run: |
          curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo npm install -g appium

      - name: Install uiautomator2 driver
        run: sudo npm install -g appium-uiautomator2-driver

      - name: Start Appium Server
        run: |
          chmod +x ./scripts/RunAppiumServer.sh
          ./scripts/RunAppiumServer.sh
        shell: bash

      - name: Install Android SDK
        run: |
          chmod +x ./scripts/install-android-sdk.sh
          ./scripts/install-android-sdk.sh
        shell: bash

      - name: Set up emulator
        run: |
          chmod +x ./scripts/emulator-up.sh
          ./scripts/emulator-up.sh
        shell: bash

      - name: Run Appium Tests with Maven
        run: mvn test
        working-directory: Appium2.0_Project2  # Adjust this to match your Maven project directory on GitHub

      - name: Appium Cleanup
        run: |
          # Any cleanup tasks if needed
          # For example, stopping Appium server or cleaning up temporary files
        shell: bash
