name: Appium Selenium Tests on Android Emulator

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Appium Selenium Tests on Android Emulator
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Download and set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '30'

      - name: Kill any running ADB server
        run: adb kill-server || true

      - name: Start ADB server
        run: adb start-server

      - name: Wait for ADB server to start
        run: |
          sleep 5
          adb devices

      - name: Start Android Emulator
        run: |
          emulator -avd Pixel_6_API_30 -no-window -no-audio -no-boot-anim -accel auto -gpu host &
          sleep 5

      - name: Wait for Emulator to start
        run: |
          echo "Waiting for emulator to start"
          adb wait-for-device
          adb shell input keyevent 82  # Simulate unlock screen
          adb shell getprop sys.boot_completed | findstr /C:"1"

      - name: Verify Emulator is running
        run: adb devices

      - name: List open ports (for debugging)
        run: netstat -ano | findstr LISTENING || echo "No listening ports found"

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Appium
        run: npm install -g appium

      - name: Start Appium Server
        run: appium &
        env:
          APPIUM_HOME: C:\Users\runneradmin\AppData\Roaming\npm\node_modules\appium

      - name: Wait for Appium Server to start
        run: sleep 10

      - name: Run Appium Tests
        run: mvn test -Denv=local
