name: Run Android tests in GitHub Runner

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [30]
        target: [default]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          architecture: 'x64'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
          architecture: 'x64'
          check-latest: false
        env:
          JAVA_HOME: /Users/runner/hostedtoolcache/Java_Adopt_jdk/17.0.11-9/x64/Contents/Home

      - name: Install Appium
        run: |
          npm install -g appium@latest
          appium -v
          appium &>/dev/null &

      - name: Set up Android SDK environment
        run: |
          export ANDROID_HOME=$RUNNER_TOOL_CACHE/Android/sdk
          export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH

      - name: Install Android SDK packages
        run: |
          sdkmanager --install 'build-tools;29.0.2' 'platform-tools' 'platforms;android-30' 'emulator'

      - name: Run Appium Tests
        uses: reactivecircus/android-emulator-runner@v1
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6 API 30
          script: mvn clean test -Pandroid
