name: Run Android tests in GitHub Runner

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install Appium
        run: |
          npm install -g appium@2.5.1
          appium -v
        shell: bash

      - name: Install UIAutomator2 driver for Appium
        run: |
          appium driver install uiautomator2@3.0.1
        shell: bash

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Android SDK packages
        run: |
          sdkmanager --install 'system-images;android-34;google_apis;x86_64'
          sdkmanager --install 'platform-tools'
          sdkmanager --install 'emulator'

      - name: Accept SDK licenses
        run: |
          echo y | sdkmanager --licenses

      - name: Create AVD
        run: |
          echo no | avdmanager create avd -n test -k "system-images;android-34;google_apis;x86_64" --force

      - name: Start emulator
        run: |
          emulator -avd test -no-window -no-audio -no-boot-anim &
          Start-Sleep -Seconds 60
        env:
          ANDROID_SDK_ROOT: C:\Users\runneradmin\AppData\Local\Android\Sdk

      - name: Check Android emulator status
        run: adb devices

      - name: Start Appium server
        run: |
          appium &
        shell: bash
        env:
          ANDROID_HOME: C:\Users\runneradmin\AppData\Local\Android\Sdk
          ANDROID_SDK_ROOT: C:\Users\runneradmin\AppData\Local\Android\Sdk

      - name: Verify Appium server is running
        run: |
          curl http://127.0.0.1:4723/status
          if ($?) { Write-Host "Appium server is running" } else { Write-Host "Appium server is not running"; exit 1 }
        shell: pwsh

      - name: Print Android SDK Paths
        run: |
          echo "ANDROID_HOME: $env:ANDROID_HOME"
          echo "ANDROID_SDK_ROOT: $env:ANDROID_SDK_ROOT"
        shell: pwsh

      - name: Run Android Tests
        run: |
          echo "JAVA_HOME: $env:JAVA_HOME"
          mvn -Dtest=TestRunner test
        env:
          ANDROID_HOME: C:\Users\runneradmin\AppData\Local\Android\Sdk
          ANDROID_SDK_ROOT: C:\Users\runneradmin\AppData\Local\Android\Sdk

      - name: Display Appium Logs
        run: |
          type appium.log
