name: Android Emulator Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Install Maven dependencies
        run: mvn install

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '34'

      - name: Install emulator
        run: |
          echo "y" | sdkmanager --install "emulator"
          echo "y" | sdkmanager --install "platforms;android-34"
          echo "y" | sdkmanager --install "system-images;android-34;default;x86_64"

      - name: Create and start emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          profile: default
          avd-name: Pixel_5
          emulator-options: -no-audio -no-window

      - name: Wait for emulator to start
        run: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'

      - name: Run Maven Tests
        run: mvn test

