name: Run android tests in GitHub Runner

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [34]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - run: |
          npm install -g appium@v2.5.1
          appium -v
          appium &>/dev/null &

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '31'

      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: run android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            export PATH=$PATH:/Users/KhaledBEDOUI/AppData/Local/Android/Sdk/platform-tools
            mvn clean test -Pandroid

      - name: Set up ADB path
        run: echo "/Users/KhaledBEDOUI/AppData/Local/Android/Sdk/platform-tools" >> $GITHUB_PATH

    env:
      JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/17.0.11-9/x64
      ANDROID_HOME: /Users/KhaledBEDOUI/Library/Android/sdk
