name: Android Instrumented Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - apiLevel: 32
            emuTag: google_apis
            arch: x86_64
          - apiLevel: 30
            emuTag: google_apis
            arch: x86
          - apiLevel: 28
            emuTag: default
            arch: x86
          - apiLevel: 23
            emuTag: default
            arch: x86

    env:
      CI: true
      ANDROID_AVD: emulator
      _FORCE_LOGS: 1
      TEST_PASS_THRESHOLD: 10

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Java
        run: |
          sudo apt update
          sudo apt install openjdk-17-jdk -y
          sudo update-java-alternatives --set java-17-openjdk-amd64

      - name: Install Android SDK
        run: |
          ANDROID_HOME=/opt/androidsdk
          mkdir -p $ANDROID_HOME
          cd ~ && wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
          sudo apt install unzip -y && unzip sdk-tools-linux-4333796.zip -d $ANDROID_HOME
          echo "export ANDROID_HOME=$ANDROID_HOME" >> ~/.bashrc
          echo 'export SDK=$ANDROID_HOME' >> ~/.bashrc
          echo 'export PATH=$SDK/emulator:$SDK/tools:$SDK/tools/bin:$SDK/platform-tools:$PATH' >> ~/.bashrc
          source ~/.bashrc
          yes | $ANDROID_HOME/tools/bin/sdkmanager "platform-tools" "platforms;android-${{ matrix.apiLevel }}" "emulator"
          yes | $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-${{ matrix.apiLevel }};google_apis;x86_64"
          emulator -version

      - name: Create and Start Emulator
        run: |
          avd_name="Pixel_5_API_34"
          echo no | $ANDROID_HOME/tools/bin/avdmanager create avd -n $avd_name -k "system-images;android-${{ matrix.apiLevel }};google_apis;x86_64"
          $ANDROID_HOME/emulator/emulator -avd $avd_name -no-audio -no-window -no-accel &

      - name: Wait for Emulator to Start
        run: |
          adb wait-for-device
          adb shell input keyevent 82

      - run: nohup adb logcat > logcat.log &
        name: Capture logcat

      - name: Ensure Maven is installed
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Run Maven tests
        run: mvn test -Denv=local

      - name: Save logcat output
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: logcat-api${{ matrix.apiLevel }}
          path: logcat.log
