name: Run Android tests in GitHub Runner

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest  # Utilisez une machine Linux pour une meilleure compatibilité avec les outils Android
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install Appium
        run: |
          npm install -g appium@latest
          appium -v

      - name: Install Appium Doctor
        run: |
          npm install -g appium-doctor
          appium-doctor --version

      - name: Install UIAutomator2 driver for Appium
        run: |
          appium driver install uiautomator2@latest

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-levels: 34
          components: platform-tools, emulator, system-images;android-34;google_apis;x86_64

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Create AVD
        run: |
          echo no | avdmanager create avd -n test -k "system-images;android-34;google_apis;x86_64" --force

      - name: Start emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd test -no-window -no-audio &
          adb wait-for-device
          adb shell input keyevent 82
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}

      - name: Verify emulator is running
        run: |
          adb devices

      - name: Run Appium Doctor
        run: |
          appium-doctor --android

      - name: Start Appium server
        run: |
          appium &
          sleep 10  # Wait for the Appium server to start

      - name: Verify Appium server is running
        run: |
          curl http://127.0.0.1:4723/status

      - name: Run Android Tests
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          echo "ANDROID_HOME: $ANDROID_HOME"
          echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
          echo "Running Maven tests..."
          mvn test -Denv=local
          echo "Maven tests completed."
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
