name: Appium Tests with Maven

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download and extract Android SDK
        uses: actions/setup-android@v2
        with:
          sdk-platform: '30'

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install Appium
        run: npm install -g appium

      - name: Build and assemble APK
        run: mvn clean install -DskipTests=true

      - name: Start Appium Server
        run: appium &

      - name: Run Appium Tests
        run: mvn test

      - name: Stop Appium Server
        run: pkill -f appium
