name: Run Android tests in GitHub Runner

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "Setting up environment variables"
          echo "ANDROID_HOME=$HOME/Library/Android/sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin" >> $GITHUB_ENV
          echo "ANDROID_HOME is set to: $ANDROID_HOME"
          echo "PATH is set to: $PATH"
        shell: bash

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install Appium
        run: |
          npm install -g appium@latest
          appium -v
        shell: bash

      - name: Install Appium Doctor
        run: |
          npm install -g appium-doctor
          appium-doctor --version
        shell: bash

      - name: Install UIAutomator2 driver for Appium
        run: |
          appium driver install uiautomator2@3.0.1
        shell: bash

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: |
          sdkmanager --install 'system-images;android-34;google_apis;x86_64'
          sdkmanager --install 'platform-tools'
          sdkmanager --install 'emulator'
        shell: bash

      - name: Accept SDK licenses
        run: |
          yes | sdkmanager --licenses
        shell: bash

      - name: Run Appium Doctor
        run: |
          appium-doctor --android
        shell: bash

      - name: Create AVD
        run: |
          echo no | avdmanager create avd -n Pixel_5_API_34 -k "system-images;android-34;google_apis;x86_64" --force
        timeout-minutes: 10
        shell: bash

      - name: List available AVDs
        run: |
          avdmanager list avd
          ls $HOME/.android/avd
        shell: bash

      - name: Start emulator
        run: |
          emulator -avd Pixel_5_API_34 -no-audio -no-window &
          adb wait-for-device
          sleep 60
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}
        shell: bash

      - name: Verify emulator is running
        run: |
          adb devices
        shell: bash

      - name: Start Appium server
        run: |
          appium &
        shell: bash
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}

      - name: Verify Appium server is running
        run: |
          curl http://127.0.0.1:4723/status
          if [ $? -eq 0 ]; then echo "Appium server is running"; else echo "Appium server is not running"; exit 1; fi
        shell: bash

      - name: Run Android Tests
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          echo "ANDROID_HOME: $ANDROID_HOME"
          echo "ANDROID_SDK_ROOT: $ANDROID_HOME"
          ls -la
          echo "Running Maven tests..."
          mvn test -Denv=local
          echo "Maven tests completed."
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}
        shell: bash
