name: appium-android

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [30]
        target: [default]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
          unzip sdk-tools.zip -d $HOME/android-sdk
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          yes | $ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-30" "emulator" "build-tools;29.0.2"

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Appium
        run: npm install -g appium@v2.5.1

      - name: Start Appium Server
        run: appium &

      - name: Run Appium Tests
        uses: reactivecircus/android-emulator-runner@v1
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Pixel_6_API_30
          script: mvn clean test

      - name: Stop Appium Server
        run: pkill -f appium
