name: Appium Android Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

jobs:
  test-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        android-version: [11]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install dependencies
        run: |
          npm ci

      - name: Install Appium
        run: |
          npm install -g appium

      - name: Run tests
        env:
          ANDROID_VERSION: ${{ matrix.android-version }}
          APK_PATH: ./src/main/resources/ApiDemos-debug.apk
        run: |
          echo "Starting test execution for Android ${ANDROID_VERSION}"
          appium doctor
          appium run android --app ${APK_PATH} --version $ANDROID_VERSION
          echo "Test execution completed"
