name: Android CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Android SDK
        run: |
          sudo apt update
          sudo apt install openjdk-17-jdk -y
          sudo update-java-alternatives --set java-17-openjdk-amd64
          cd ~ && wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
          ANDROID_HOME=/opt/androidsdk
          mkdir -p $ANDROID_HOME
          sudo apt install unzip -y && unzip sdk-tools-linux-4333796.zip -d $ANDROID_HOME
          echo "export ANDROID_HOME=$ANDROID_HOME" >> ~/.bashrc
          echo 'export SDK=$ANDROID_HOME' >> ~/.bashrc
          echo 'export PATH=$SDK/emulator:$SDK/tools:$SDK/tools/bin:$SDK/platform-tools:$PATH' >> ~/.bashrc
          source ~/.bashrc
          yes | sudo sdkmanager "platform-tools" "platforms;android-30" "emulator"
          yes | sudo sdkmanager "system-images;android-30;google_apis;x86_64"
          emulator -version

      - name: Set up emulator
        run: |
          # Start emulator in background
          emulator -avd Pixel_6_API_30 -no-audio -no-window -no-accel &

          # Wait for emulator to be ready
          boot_completed=""
          until [ "$boot_completed" = "1" ]; do
            boot_completed=$(adb -e shell getprop sys.boot_completed | tr -d '\r')
            sleep 1
          done

      - name: Run Appium Server
        run: |
          npm install -g appium@2.5.1
          appium driver install uiautomator2
          appium driver install espresso
          appium --log-level debug &

      - name: Run tests
        run: |
          mvn test -Denv=local
