name: Run Appium Tests

on:
  push:
    branches:
      - master

jobs:
  appium-tests:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5554:5554
          - 5555:5555
          - 4723:4723

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Wait for emulator to be ready
        run: |
          sleep 60  # Ajuste ce délai si nécessaire pour t'assurer que l'émulateur est prêt

      - name: Run Appium Tests
        run: docker-compose logs tests  # Regarde les logs de l'exécution des tests
