name: Run Android tests on Windows

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install Appium
        run: |
          npm install -g appium@v2.5.1
          appium -v

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-levels: 34
          target: default
          arch: x86_64
          channel: stable

      - name: Install Android SDK packages
        run: |
          sdkmanager --install 'system-images;android-34;google_apis;x86_64'
          sdkmanager --install 'platform-tools'
          sdkmanager --install 'emulator'
          sdkmanager --licenses

      - name: Create AVD
        run: |
          echo "no" | avdmanager create avd -n test -k "system-images;android-34;google_apis;x86_64" --force

      - name: Start emulator
        run: |
          emulator -avd test -no-window -no-audio -no-boot-anim &
        env:
          ANDROID_SDK_ROOT: C:\Users\runneradmin\AppData\Local\Android\Sdk

      - name: Wait for emulator to boot
        run: |
          adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
          adb shell input keyevent 82
        env:
          ANDROID_SDK_ROOT: C:\Users\runneradmin\AppData\Local\Android\Sdk

      - name: Run Android tests
        run: |
          mvn clean test -Pandroid
        env:
          JAVA_HOME: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\17.0.0-4\x64
          ANDROID_HOME: C:\Users\runneradmin\AppData\Local\Android\Sdk
          ANDROID_SDK_ROOT: C:\Users\runneradmin\AppData\Local\Android\Sdk
          PATH: ${{ env.PATH }};C:\Users\runneradmin\AppData\Local\Android\Sdk\platform-tools

