name: Appium CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ui-tests:
    strategy:
      matrix:
        api-level: [34]
        target: [default]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Install the Emulator
        run: |
          chmod +x ./scripts/RunAppiumServer.sh
          ./scripts/RunAppiumServer.sh
        shell: bash

      - name: Build and Test with Maven
        run: mvn clean test
