name: Java Selenium Appium Tests

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 1
        uses: actions/setup-java@v3
        with:
          java-version: '1'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Install dependencies
        run: mvn -B dependency:resolve dependency:resolve-plugins

      - name: Run tests
        run: mvn test

      # Add additional steps to start Appium server if necessary

      - name: Start Appium Server
        run: appium &

      - name: Run Selenium Appium tests
        run: mvn -Dtest=TestRunner test
