name: Appium CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [34] # Mettez à jour avec la version Android que vous utilisez
        target: [default]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Install and Run Appium Server
        run: |
          chmod +x ./scripts/RunAppiumServer.sh # Assurez-vous que le chemin est correct
          ./scripts/RunAppiumServer.sh

      - name: Run Appium Tests
        uses: reactivecircus/android-emulator-runner@v1
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6 # Personnalisez selon vos besoins
          script: mvn clean test -Pandroid # Remplacez par votre commande de test
