name: Java Selenium Appium Tests

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 17 and Android SDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
        env:
          ANDROID_HOME: ${{ runner.workspace }}/android-sdk-linux

      - name: Install dependencies
        run: mvn -B dependency:resolve dependency:resolve-plugins

      - name: Install and configure Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 14
          arch: x86
          profile: Pixel_5
          force-avd-creation: false
          emulator-options: -no-audio -no-window
          disable-animations: true
          script: echo "Emulator is ready."

      - name: Start Android Emulator
        run: |
          emulator -avd Pixel_5 -no-audio -no-window &
          android-wait-for-emulator

      - name: Run tests
        run: mvn test

      - name: Start Appium Server
        run: appium &

      - name: Run Selenium Appium tests
        run: mvn -Dtest=TestRunner test
