name: Run Android tests with Appium on Emulator

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [34]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install Appium and configure Android SDK
        run: |
          chmod +x ./scripts/RunAppiumServer.sh
          ./scripts/RunAppiumServer.sh
          sudo chown $USER:$USER /usr/local/lib/android/sdk -R
          yes | sdkmanager --licenses > /dev/null
          sdkmanager --install 'build-tools;33.0.0' platform-tools 'platforms;android-34' emulator 'system-images;android-34;google_apis;x86' > /dev/null

      - name: Launch Android Emulator
        uses: reactivecircus/android-emulator-runner@v2.27.0
        with:
          api-level: ${{ matrix.api-level }}
          profile: Pixel_5
          target: google_apis

      - name: Run Appium Android tests
        run: ./scripts/run_on_emulator.sh
